server:
  port: 8083

spring:
  application:
    name: demo3

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
feign:
  hystrix:
    enabled: true